=== chandru4664/Classworks_JEE1/Day 19/DOM/RightSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="players" type="TeamType"/>
	
	<xsd:complexType name="TeamType">
			<xsd:sequence>
				<xsd:element name="player" type="PlayerType" maxOccurs="unbounded"/>
			</xsd:sequence>
	</xsd:complexType>
	
	
	<xsd:complexType name="PlayerType">
		<xsd:sequence>
			<xsd:element name="playerName" type="NameType"/>
			<xsd:element name="fatherName" type="NameType" minOccurs="0"/>
			<xsd:element name="dateOfBirth" type="xsd:date"/>
			<xsd:element name="address" type="AddressType"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:ID" use="required"/>
	</xsd:complexType>	
	
	
	<xsd:complexType name="NameType">
		<xsd:sequence>
			<xsd:element name="firstName" type="FirstNameType"/>
			<xsd:element name="midName" type="xsd:string"/>
			<xsd:element name="lastName" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
	
	
	<xsd:complexType name="AddressType">
		<xsd:all>
			<xsd:element name="street" type="StreetAttrType"/>
			<xsd:element name="city" type="xsd:string"/>						
			<xsd:element name="pin" type="PinType"/>
		</xsd:all>
	</xsd:complexType>
		
	<xsd:simpleType name="FirstNameType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="20"/>
			<xsd:minLength value="3"/>
		</xsd:restriction>
	</xsd:simpleType>	

	<xsd:simpleType name="PinCodeBody">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="0"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="PinType">
		<xsd:simpleContent>
			<xsd:extension base="PinCodeBody">
				<xsd:attribute name="code" use="required">
					<xsd:simpleType>
						<xsd:restriction base="xsd:integer">
							<xsd:minExclusive value="99999"/>
							<xsd:maxExclusive value="999999"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
  </xsd:complexType>
	
	
	
	<xsd:simpleType name="StreetType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-zA-Z0-9]{3,50}"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="StreetAttrType">
		<xsd:simpleContent>
			<xsd:extension base="StreetType">
				<xsd:attribute name="no" type="xsd:integer" use="required"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	
</xsd:schema>

=== chandru4664/Classworks_JEE1/Day 19/DOM/Players.xml
<?xml version="1.0" encoding="UTF-8"?>                                                                                                                                                                                                                              
<players  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RightSchema.xsd">
	<player id="P1">
		<playerName>
			<firstName>SachineRamesh</firstName>
			<midName>Ramesh</midName>
			<lastName>Tendulkar</lastName>	
		</playerName>
		<dateOfBirth>1973-04-24</dateOfBirth>
		<address>
			<pin code="524126"/>
			<street no="1">1stMain</street>
			<city>Mumbai</city>
		</address>
	</player>
	<player id="P2">
		<playerName>
			<firstName>Mahindra</firstName>
			<midName>Singh</midName>
			<lastName>Dhoni</lastName>	
		</playerName>
		<dateOfBirth>1983-04-24</dateOfBirth>
		<address>
			<pin code="600062"/>
			<street no="2">GrandTrunkRoad</street>
			<city>Jarkhand</city>	
		</address>
	</player>
	<player id="P3">
		<playerName>
			<firstName>Anil</firstName>
			<midName></midName>
			<lastName>Kumble</lastName>	
		</playerName>
		<dateOfBirth>1965-04-24</dateOfBirth>
		<address>
			<pin code="600062"/>
			<street no="1">Silkboard</street>
			<city>Mumbai</city>
		</address>
	</player>
	<player id="P4">
		<playerName>
			<firstName>Thirupathi</firstName>
			<midName></midName>
			<lastName>rayudu</lastName>	
		</playerName>
		<dateOfBirth>1984-04-24</dateOfBirth>
		<address>
			<pin code="524001"/>
			<street no="8">KTRoad</street>
			<city>Thirupathi</city>
		</address>
	</player>
</players>
