=== chandru4664/Classworks_JEE1/Day 19/SAX/DefaultTest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="cricket" type="crick_ty" />

<xsd:complexType name="crick_ty">

<xsd:sequence>

  <xsd:element name="batsmen" type="batsmen_ty"/>

  <xsd:element name="bowlers" type="bowlers_ty"/>

 </xsd:sequence>

</xsd:complexType>

<xsd:complexType name="batsmen_ty">

  <xsd:sequence>
   <xsd:element name="batsman" type="xsd:string" minOccurs="1" maxOccurs="unbounded" default="Tendulkar"/>
  </xsd:sequence>

</xsd:complexType>

<xsd:complexType name="bowlers_ty">

  <xsd:sequence>
   <xsd:element name="bowler" type="xsd:string" minOccurs="1" maxOccurs="unbounded" />
  </xsd:sequence>

</xsd:complexType>

</xsd:schema>

=== chandru4664/Classworks_JEE1/Day 19/SAX/cricki.xml
<?xml version="1.0" encoding="UTF-8" ?>
<cricket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="DefaultTest.xsd">
     <batsmen>
        <batsman>dhawan</batsman>
        <batsman>rohit</batsman>
        <batsman>Karthik</batsman>
        <batsman>Dhoni</batsman>
        <batsman>raina</batsman>
        <batsman></batsman>
        
      </batsmen>
      <bowlers>
         <bowler>Aswin</bowler>
         <bowler>Jadejha</bowler>
         <bowler>Bhuvanesh</bowler>
         <bowler>Umesh Yadav</bowler>
         <bowler>Ishanth Sarma</bowler>
       </bowlers>
</cricket>
