=== chandru4664/Classworks_JEE1/Day 19/SAX/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
			targetNamespace="http://www.example.org/students" 
			xmlns:tns="http://www.example.org/students" 
			elementFormDefault="qualified">
			
			<xsd:element name="students" type="student_ty"/>
			<xsd:complexType name="student_ty">
				<xsd:sequence>
					<xsd:element name="stud" type="stud_ty" maxOccurs="unbounded" minOccurs="1"/>
				</xsd:sequence>
			</xsd:complexType>
			<xsd:complexType name="stud_ty">
				<xsd:sequence>
					<xsd:element name="studName" type="xsd:string"/>
					<xsd:element name="department" type="xsd:string"/>
					<xsd:element name="phone" type="phone_ty"/>
				</xsd:sequence>
				<xsd:attribute name="regNo" type="xsd:ID"  use="required"></xsd:attribute>
			</xsd:complexType>
			<xsd:complexType name="phone_ty">
				<xsd:sequence>
					<xsd:element name="mobile" type="xsd:string" minOccurs="0"></xsd:element>
				</xsd:sequence>
			</xsd:complexType>
</xsd:schema>

=== chandru4664/Classworks_JEE1/Day 19/SAX/students.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><students xmlns="http://www.example.org/students" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/students students.xsd">
			
			<stud regNo="123">
				<studName>Hari</studName>
				<department>MCA</department>		 
				<phone>
					<mobile>123456789</mobile>
				</phone>
			
			</stud>
			<stud regNo="124">
				<studName>SriHari</studName>
				<age>25</age>
				<department>BSC</department>
				<phone>
					<mobile>987654321</mobile>
				</phone>
			</stud>
			</students>
